project:
  type: website

website:
  title: "C2C Kim Final Project - Penguin Exploration"
  navbar:
    background: pink
    left:
      - href: About.qmd
        text: About
      - href: model.qmd
        text: Model
      - href: eda.qmd
        text: EDA

format:
  html:
    css: styles.css
