project:
  type: website

website:
  navbar:
    background: pink
    left:
      - href: about.qmd
        text: About
      - href: model.qmd
        text: Model
      - href: eda.qmd
        text: EDA

format:
  html:
    css: styles.css
